import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'hi' | 'pa';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations = {
  en: {
    // Header
    'header.title': 'AgriVikas',
    'header.subtitle': 'Smart Crop Advisory for Small & Marginal Farmers',
    'header.home': 'Home',
    'header.about': 'About Us',
    'header.features': 'Features',
    'header.schemes': 'Schemes',
    'header.contact': 'Contact',
    'header.signIn': 'Sign In',
    'header.guestLogin': 'Guest Login',
    'header.menu': 'Menu',
    
    // Language Selector
    'lang.english': 'English',
    'lang.hindi': 'हिंदी (Hindi)',
    'lang.punjabi': 'ਪੰਜਾਬੀ (Punjabi)',
    
    // Hero Section
    'hero.tagline': 'Empowering Farmers with Smart Crop Decisions, Water Savings & Timely Alerts',
    'hero.description': 'Get personalized crop advisory, irrigation alerts, and AI-powered health detection in your language',
    'hero.exploreGuest': 'Explore as Guest',
    'hero.signInDashboard': 'Sign In to Your Dashboard',
    
    // Features Section
    'features.title': 'Key Features',
    'features.subtitle': 'Cutting-edge technology designed specifically for Indian farmers',
    'features.scrollCue': 'Explore AgriVikas Features',
    'features.irrigation.title': 'Smart Irrigation Alerts',
    'features.irrigation.description': 'Get weather-based irrigation recommendations to save water and energy',
    'features.irrigation.badge': 'Save 40% Water',
    'features.health.title': 'AI Crop Disease Detection',
    'features.health.description': 'Upload leaf photos and detect diseases early using machine learning',
    'features.health.badge': 'Early Detection',
    'features.advisory.title': 'Smart Crop Advisory',
    'features.advisory.description': 'Personalized crop suggestions based on soil, season, and weather',
    'features.advisory.badge': 'AI Powered',
    'features.schemes.title': 'Government Scheme & Subsidy Awareness',
    'features.schemes.description': 'Stay updated on PM-KISAN, MSP, and equipment subsidies. Bridges the information gap for small & marginal farmers',
    'features.schemes.badge': 'Stay Informed',
    'features.diversification.title': 'Crop Diversification Support',
    'features.diversification.description': 'Promote soil fertility and water conservation by shifting to sustainable crops',
    'features.diversification.badge': 'Sustainable',
    'features.multilingual.title': 'Multilingual Communication',
    'features.multilingual.description': 'Access advisories in Punjabi, Hindi, and English—even on feature phones via App, SMS, and Voice',
    'features.multilingual.badge': '3 Languages',
    
    // About Section
    'about.title': 'About AgriVikas',
    'about.description1': 'AgriVikas is a digital platform designed to empower small and marginal farmers across India with data-driven agricultural insights. Our mission is to bridge the technology gap in rural farming communities and help farmers make informed decisions about crop management, irrigation, and pest control.',
    'about.description2': 'Built with support from agricultural experts and powered by AI, we provide timely, accurate, and actionable advice in multiple Indian languages, ensuring every farmer can benefit from modern technology.',
    
    // Schemes Section
    'schemes.title': 'Government Schemes',
    'schemes.subtitle': 'Stay updated with the latest agricultural schemes and subsidies',
    'schemes.description': 'Information about PM-KISAN, Soil Health Card Scheme, Pradhan Mantri Fasal Bima Yojana, and other government initiatives will be available here soon.',
    
    // Contact Section
    'contact.title': 'Get in Touch',
    'contact.description': 'Have questions or need support? We\'re here to help farmers across India.',
    'contact.button': 'Contact Support',
    
    // Footer
    'footer.collaboration': 'In collaboration with Ministry of Agriculture & Farmers Welfare (Demo)',
    'footer.copyright': '© 2025 AgriVikas – Empowering India\'s Farmers',
    
    // Dashboard
    'dashboard.welcome': 'Welcome to AgriVikas Dashboard',
    'dashboard.greeting': 'Hello',
    'dashboard.message': 'Your personalized crop advisory dashboard is coming soon.',
    
    // Auth Page
    'auth.getStarted': 'Get Started',
    'auth.enterEmail': 'Enter your email to log in or sign up',
    'auth.emailPlaceholder': 'name@example.com',
    'auth.or': 'Or',
    'auth.continueGuest': 'Continue as Guest',
    'auth.checkEmail': 'Check your email',
    'auth.codeSent': 'We\'ve sent a code to',
    'auth.didntReceive': 'Didn\'t receive a code?',
    'auth.tryAgain': 'Try again',
    'auth.verifyCode': 'Verify code',
    'auth.verifying': 'Verifying...',
    'auth.useDifferentEmail': 'Use different email',
    'auth.securedBy': 'Secured by',
    
    // Not Found
    'notFound.title': '404',
    'notFound.message': 'Page Not Found',
    
    // Chatbot
    'chatbot.title': 'AgriVikas Smart Voice Assistant',
    'chatbot.placeholder': 'Ask me about weather, irrigation, or crop help…',
    'chatbot.inputPlaceholder': 'Type your message...',
    'chatbot.voiceInput': 'Voice Input',
    'chatbot.recording': 'Recording...',
    'chatbot.error.microphone': 'Microphone access denied or unavailable',
    'chatbot.error.notSupported': 'Speech recognition not supported in this browser',
    'chatbot.clearChat': 'Clear Chat',
    
    // Dashboard Navigation
    'dashboard.title': 'Dashboard',
    'dashboard.nav.home': 'Dashboard',
    'dashboard.nav.profile': 'My Profile',
    'dashboard.nav.advisory': 'Smart Crop Advisory',
    'dashboard.nav.irrigation': 'Irrigation Alerts',
    'dashboard.nav.disease': 'Disease Detection',
    'dashboard.nav.schemes': 'Govt Schemes & Subsidies',
    'dashboard.nav.mandi': 'Mandi Prices',
    'dashboard.nav.insights': 'Farm Insights',
    'dashboard.nav.chat': 'Chat Assistant',
    'dashboard.nav.settings': 'Settings',
    'dashboard.logout': 'Logout',
    
    // Dashboard Home
    'dashboard.home.welcome': 'Welcome',
    'dashboard.home.subtitle': 'Your personalized agricultural insights',
    'dashboard.home.weather': 'Weather Now',
    'dashboard.home.irrigation': 'Next Irrigation',
    'dashboard.home.irrigationValue': 'In {days} days',
    'dashboard.home.cropHealth': 'Crop Health Status',
    'dashboard.home.cropHealthValue': 'Good - No issues detected',
    'dashboard.home.schemes': 'New Schemes Available',
    'dashboard.home.schemesValue': '{count} schemes',
    'dashboard.home.latestSchemes': 'Latest Government Schemes',
    'dashboard.home.knowMore': 'Know More',
    
    // Dashboard Home - add these new keys after existing dashboard.home translations
    'dashboard.home.futureEnhancements': 'Future Enhancements',
    'dashboard.home.yieldPrediction': 'AI Yield Prediction',
    'dashboard.home.yieldPredictionDesc': 'Predict crop yields using AI and historical data for better planning',
    'dashboard.home.waterTracker': 'Water Usage Tracker Dashboard',
    'dashboard.home.waterTrackerDesc': 'Monitor and optimize water consumption across your farm',
    'dashboard.home.smsAccess': 'Offline SMS Access',
    'dashboard.home.smsAccessDesc': 'Get advisories via SMS for feature-phone farmers without internet',
    'dashboard.home.portalIntegration': 'Agri Punjab Portal Integration',
    'dashboard.home.portalIntegrationDesc': 'Seamless integration with data.gov.in and Punjab agriculture portal',
    'dashboard.home.comingSoon': 'Coming Soon',
    
    // Government Schemes
    'dashboard.schemes.pmkisan.title': 'PM-KISAN Yojana',
    'dashboard.schemes.pmkisan.description': 'Direct income support of ₹6,000/year to small & marginal farmers',
    'dashboard.schemes.pmfby.title': 'PMFBY Crop Insurance',
    'dashboard.schemes.pmfby.description': 'Comprehensive crop insurance against natural calamities',
    'dashboard.schemes.pmfby.coverage': 'Full Coverage',
    'dashboard.schemes.soilHealth.title': 'Soil Health Card Scheme',
    'dashboard.schemes.soilHealth.description': 'Free soil testing and nutrient management advice',
    'dashboard.schemes.soilHealth.free': 'Free Service',
    
    // Irrigation Alerts Section
    'irrigation.title': 'Smart Irrigation Alerts',
    'irrigation.subtitle': 'Weather-based irrigation recommendations to save water and energy',
    'irrigation.selectLocation': 'Select Location',
    'irrigation.weather': 'Weather',
    'irrigation.refresh': 'Refresh Weather',
    'irrigation.temperature': 'Temperature',
    'irrigation.humidity': 'Humidity',
    'irrigation.condition': 'Condition',
    'irrigation.adviceTitle': 'Irrigation Advice',
    'irrigation.clickRefresh': 'Click "Refresh Weather" to get live data and irrigation advice',
    'irrigation.weatherUpdated': 'Weather data updated successfully',
    'irrigation.usingSimulatedData': 'Using simulated data for demo',
    'irrigation.tip': 'Tip',
    'irrigation.tipText': 'Water your crops early morning or late evening for best results',
    'irrigation.bestPractices': 'Best Irrigation Practices',
    'irrigation.practice1': 'Water early morning (5-7 AM) or evening (6-8 PM) to reduce evaporation',
    'irrigation.practice2': 'Check soil moisture before irrigating - avoid overwatering',
    'irrigation.practice3': 'Use drip irrigation systems to save up to 40% water',
    'irrigation.practice4': 'Monitor weather forecasts and skip irrigation if rain is expected',
    'irrigation.advice.skipRain': '🌧️ Rain expected today — skip irrigation to save water and energy',
    'irrigation.advice.highTemp': '🌡️ High temperature and low humidity — irrigate in the evening for best results',
    'irrigation.advice.highHumidity': '💧 High humidity detected — reduce irrigation frequency to prevent fungal growth',
    'irrigation.advice.lowTemp': '❄️ Cool weather — reduce irrigation frequency as evaporation is low',
    'irrigation.advice.normal': '✅ Weather conditions are normal — irrigate as per regular schedule',
    
    // Disease Detection
    'disease.title': 'AI Crop Disease Detection',
    'disease.subtitle': 'Upload crop images for instant disease diagnosis and treatment recommendations',
    'disease.uploadTitle': 'Upload Crop Image',
    'disease.chooseImage': 'Choose Image',
    'disease.analyzeImage': 'Analyze Image',
    'disease.analyzing': 'Analyzing...',
    'disease.dragDrop': 'Drag & drop an image here, or click to select',
    'disease.fileTypes': 'JPG, PNG (max 5MB)',
    'disease.resultsTitle': 'Analysis Results',
    'disease.noResults': 'Upload and analyze an image to see results',
    'disease.confidence': 'Confidence',
    'disease.severity': 'Severity',
    'disease.treatment': 'Recommended Treatment',
    'disease.impact': 'Potential Yield Impact',
    'disease.recommendation': 'Recommendation',
    'disease.speakResult': 'Speak Result',
    'disease.requestAgronomist': 'Request Agronomist Review',
    'disease.historyTitle': 'Recent Analyses',
    'disease.noHistory': 'No analysis history yet',
    'disease.sampleImages': 'Sample Test Images',
    'disease.runSampleTest': 'Run Sample Test',
    'disease.advisoryNote': '⚠️ Results are advisory. For critical issues, consult a local agronomist.',
    'disease.fileTooLarge': 'File size exceeds 5MB limit',
    'disease.invalidFileType': 'Please upload a JPG or PNG image',
    'disease.uploadError': 'Failed to upload image. Please try again.',
    'disease.analysisError': 'Analysis failed. Please try again.',
    
    // Disease Names
    'disease.name.healthy': 'Healthy',
    'disease.name.leafBlight': 'Leaf Blight',
    'disease.name.rust': 'Rust',
    'disease.name.powderyMildew': 'Powdery Mildew',
    'disease.name.bacterialSpot': 'Bacterial Spot',
    'disease.name.earlyBlight': 'Early Blight',
    'disease.name.lateBlight': 'Late Blight',
    'disease.name.uncertain': 'Uncertain - Needs Expert Review',
    
    // Severity Levels
    'disease.severity.none': 'None',
    'disease.severity.early': 'Early Stage',
    'disease.severity.moderate': 'Moderate',
    'disease.severity.severe': 'Severe',
    'disease.severity.uncertain': 'Uncertain',
    
    // Agronomist Modal
    'disease.agronomist.title': 'Request Agronomist Review',
    'disease.agronomist.description': 'Our agricultural experts will review your case and contact you within 24 hours.',
    'disease.agronomist.phone': 'Phone Number',
    'disease.agronomist.phonePlaceholder': '+91 98765 43210',
    'disease.agronomist.farmerId': 'Farmer ID (Optional)',
    'disease.agronomist.farmerIdPlaceholder': 'Your registered farmer ID',
    'disease.agronomist.submit': 'Submit Request',
    'disease.agronomist.cancel': 'Cancel',
    'disease.agronomist.success': 'Request submitted! An agronomist will contact you soon.',
    
    // Disease Detection - New translations
    'disease.photoGuide.title': '📸 How to Take a Good Photo',
    'disease.photoGuide.step1': 'Use clear daylight',
    'disease.photoGuide.step2': 'Focus on the infected area (no background)',
    'disease.photoGuide.step3': 'Avoid blurry or shaded images',
    'disease.photoGuide.step4': 'Take both close-up and whole plant photos',
    'disease.needMoreImages': 'Please add one more image for better accuracy',
    'disease.needBothTypes': 'Please upload both close-up and full plant images',
    'disease.blurryImage': '⚠️ Image is blurry — please retake it',
    'disease.noImages': 'Please upload at least one image',
    'disease.closeup': 'Close-up',
    'disease.fullplant': 'Full Plant',
    'disease.selectImageType': 'Select Image Type',
    'disease.selectImageTypeDesc': 'Is this a close-up of the infected area or a full plant photo?',
    'disease.imageAdded': 'Image added successfully',
    'disease.imageReplaced': 'Image replaced',
    'disease.uploadProgress': 'Uploaded {count}/2 images',
    'disease.analysisComplete': 'Analysis complete!',
    
    // Detailed Recommendations
    'disease.recommendations.title': 'Detailed Treatment Recommendations',
    'disease.recommendations.cultural': 'Cultural Controls 🌱',
    'disease.recommendations.organic': 'Organic Options 🌿',
    'disease.recommendations.chemical': 'Chemical Options 💊',
    'disease.recommendations.safety': 'Safety Notes ⚠️',
    'disease.recommendations.impact': 'Estimated Impact',
    'disease.recommendations.speakAll': 'Speak All Recommendations',
    
    // Fertilizer & Soil Health
    'disease.fertilizer.title': 'Fertilizer & Soil Health Suggestion',
    'disease.fertilizer.deficiency': 'Possible Nutrient Deficiency',
    'disease.fertilizer.shortTerm': 'Short-term Fix',
    'disease.fertilizer.longTerm': 'Long-term Solution',
    'disease.fertilizer.soilTest': 'Locate Nearest Soil Testing Center',
    'disease.fertilizer.noDeficiency': 'No nutrient deficiency detected. Maintain regular fertilization schedule.',
    
    // Chatbot - Disease Detection Integration
    'chatbot.disease.uploadPrompt': 'Please upload a clear photo of your crop leaf for analysis 🌿. I\'ll help you identify any diseases!',
    'chatbot.disease.analysisComplete': 'Analysis complete!',
    'chatbot.disease.viewReport': 'View Full Report',
    'chatbot.disease.soilTip': 'Soil Tip',
    
    // Smart Crop Advisory
    'advisory.title': 'Smart Crop Advisory',
    'advisory.subtitle': 'Get personalized crop recommendations for sustainable farming',
    'advisory.getAdvisory': 'Get Advisory',
    'advisory.landArea': 'Land Area (acres)',
    'advisory.soilType': 'Soil Type',
    'advisory.currentCrop': 'Current Crop',
    'advisory.district': 'District',
    'advisory.waterAvailability': 'Water Availability',
    'advisory.recommendedCrops': 'Recommended Crops',
    'advisory.advice': 'Farming Advice',
    'advisory.cropComparison': 'Crop Comparison',
    'advisory.waterUse': 'Water Use',
    'advisory.profit': 'Profit Potential',
    'advisory.soilImpact': 'Soil Impact',
    'advisory.speakAdvice': 'Speak Advice',
    'advisory.history': 'Advisory History',
    
    // Mandi Prices
    'mandi.title': 'Live Mandi Prices',
    'mandi.subtitle': 'Real-time wholesale market prices of crops from the official Government of India AGMARKNET data (data.gov.in)',
    'mandi.live': 'LIVE',
    'mandi.offline': 'Setup Needed',
    'mandi.chooseCrops': 'Choose Crops & District',
    'mandi.district': 'District',
    'mandi.getPrices': 'Get Live Prices',
    'mandi.market': 'Market',
    'mandi.variety': 'Variety',
    'mandi.minPrice': 'Min',
    'mandi.maxPrice': 'Max',
    'mandi.modalPrice': 'Modal Price',
    'mandi.arrivalDate': 'Arrival Date',
    'mandi.unit': 'Unit',
    'mandi.updated': 'Updated',

    // Government Schemes
    'schemes.findSchemes': 'Find Schemes',
    'schemes.farmerCategory': 'Farmer Category',
    'schemes.cropType': 'Crop Type',
    'schemes.district': 'District',
    'schemes.irrigationMethod': 'Irrigation Method',
    'schemes.recommendedSchemes': 'Recommended Schemes',
    'schemes.history': 'Search History',
    'schemes.selectCategory': 'Select category',
    'schemes.selectCrop': 'Select crop',
    'schemes.selectDistrict': 'Select district',
    'schemes.selectMethod': 'Select method',
    'schemes.optional': 'Optional',
    'schemes.searching': 'Searching...',
    'schemes.eligibility': 'Eligibility',
    'schemes.whyScheme': 'Why This Scheme?',
    'schemes.applyNow': 'Apply Now',
    'schemes.enterDetails': 'Enter your details to find relevant government schemes',
    'schemes.clickToView': 'Click any search to view schemes again',
    'schemes.schemesFound': 'schemes found',
    'schemes.farmer': 'Farmer',
    'schemes.viewing': '✓ Viewing',
    'schemes.fillRequired': 'Please fill required fields',
    'schemes.foundSuccess': 'Schemes found!',
    'schemes.findFailed': 'Failed to find schemes',
    'schemes.loadedHistory': 'Schemes loaded from history',
    
    // Farmer Profile
    'profile.title': 'Farmer Profile',
    'profile.subtitle': 'Complete your profile for personalized recommendations',
    'profile.fullName': 'Full Name',
    'profile.district': 'District',
    'profile.landArea': 'Land Area (acres)',
    'profile.soilType': 'Soil Type',
    'profile.waterAvailability': 'Water Availability',
    'profile.crops': 'Crops Grown',
    'profile.language': 'Preferred Language',
    'profile.saveProfile': 'Save Profile',
    'profile.updateProfile': 'Update Profile',
    'profile.profileSaved': '✅ Farmer profile saved successfully! Personalized advice activated.',
    'profile.profileUpdated': '✅ Profile updated successfully!',
    'profile.fillAllFields': 'Please fill all required fields',
    'profile.selectDistrict': 'Select your district',
    'profile.selectSoilType': 'Select soil type',
    'profile.selectWaterAvailability': 'Select water availability',
    'profile.selectCrops': 'Select crops you grow',
    'profile.low': 'Low',
    'profile.medium': 'Medium',
    'profile.high': 'High',
    'profile.loamy': 'Loamy',
    'profile.sandy': 'Sandy',
    'profile.clay': 'Clay',
    'profile.alluvial': 'Alluvial',
    'profile.wheat': 'Wheat',
    'profile.rice': 'Rice/Paddy',
    'profile.maize': 'Maize',
    'profile.cotton': 'Cotton',
    'profile.sugarcane': 'Sugarcane',
    'profile.pulses': 'Pulses',
    'profile.vegetables': 'Vegetables',
  },
  hi: {
    // Header
    'header.title': 'एग्रीविकास',
    'header.subtitle': 'छोटे और सीमांत किसानों के लिए स्मार्ट फसल सलाह',
    'header.home': 'होम',
    'header.about': 'हमारे बारे में',
    'header.features': 'विशेषताएं',
    'header.schemes': 'योजनाएं',
    'header.contact': 'संपर्क',
    'header.signIn': 'साइन इन',
    'header.guestLogin': 'अतिथि लॉगिन',
    'header.menu': 'मेनू',
    
    // Language Selector
    'lang.english': 'English',
    'lang.hindi': 'हिंदी (Hindi)',
    'lang.punjabi': 'ਪੰਜਾਬੀ (Punjabi)',
    
    // Hero Section
    'hero.tagline': 'स्मार्ट फसल निर्णय, जल बचत और समय पर अलर्ट के साथ किसानों को सशक्त बनाना',
    'hero.description': 'अपनी भाषा में व्यक्तिगत फसल सलाह, सिंचाई अलर्ट और एआई-संचालित स्वास्थ्य पहचान प्राप्त करें',
    'hero.exploreGuest': 'अतिथि के रूप में देखें',
    'hero.signInDashboard': 'अपने डैशबोर्ड में साइन इन करें',
    
    // Features Section
    'features.title': 'मुख्य विशेषताएं',
    'features.subtitle': 'भारतीय किसानों के लिए विशेष रूप से डिज़ाइन की गई अत्याधुनिक तकनीक',
    'features.scrollCue': 'एग्रीविकास विशेषताएं देखें',
    'features.irrigation.title': 'स्मार्ट सिंचाई अलर्ट',
    'features.irrigation.description': 'पानी और ऊर्जा बचाने के लिए मौसम-आधारित सिंचाई सिफारिशें प्राप्त करें',
    'features.irrigation.badge': '40% पानी बचाएं',
    'features.health.title': 'एआई फसल रोग पहचान',
    'features.health.description': 'पत्ती की तस्वीरें अपलोड करें और मशीन लर्निंग का उपयोग करके रोगों का जल्दी पता लगाएं',
    'features.health.badge': 'शीघ्र पहचान',
    'features.advisory.title': 'स्मार्ट फसल सलाह',
    'features.advisory.description': 'मिट्टी, मौसम और मौसम के आधार पर व्यक्तिगत फसल सुझाव',
    'features.advisory.badge': 'AI संचालित',
    'features.schemes.title': 'सरकारी योजना और सब्सिडी जागरूकता',
    'features.schemes.description': 'पीएम-किसान, एमएसपी और उपकरण सब्सिडी पर अपडेट रहें। छोटे और सीमांत किसानों के लिए सूचना अंतर को पाटता है',
    'features.schemes.badge': 'सूचित रहें',
    'features.diversification.title': 'फसल विविधीकरण समर्थन',
    'features.diversification.description': 'टिकाऊ फसलों की ओर स्थानांतरित करके मिट्टी की उर्वरता और जल संरक्षण को बढ़ावा दें',
    'features.diversification.badge': 'टिकाऊ',
    'features.multilingual.title': 'बहुभाषी संचार',
    'features.multilingual.description': 'ऐप, एसएमएस और वॉयस के माध्यम से पंजाबी, हिंदी और अंग्रेजी में सलाह प्राप्त करें—यहां तक कि फीचर फोन पर भी',
    'features.multilingual.badge': '3 भाषाएं',
    
    // About Section
    'about.title': 'एग्रीविकास के बारे में',
    'about.description1': 'एग्रीविकास एक डिजिटल प्लेटफ़ॉर्म है जो पूरे भारत में छोटे और सीमांत किसानों को डेटा-संचालित कृषि अंतर्दृष्टि के साथ सशक्त बनाने के लिए डिज़ाइन किया गया है। हमारा मिशन ग्रामीण कृषि समुदायों में प्रौद्योगिकी अंतर को पाटना और किसानों को फसल प्रबंधन, सिंचाई और कीट नियंत्रण के बारे में सूचित निर्णय लेने में मदद करना है।',
    'about.description2': 'कृषि विशेषज्ञों के समर्थन से निर्मित और एआई द्वारा संचालित, हम कई भारतीय भाषाओं में समय पर, सटीक और कार्रवाई योग्य सलाह प्रदान करते हैं, यह सुनिश्चित करते हुए कि हर किसान आधुनिक तकनीक से लाभान्वित हो सके।',
    
    // Schemes Section
    'schemes.title': 'सरकारी योजनाएं',
    'schemes.subtitle': 'नवीनतम कृषि योजनाओं और सब्सिडी के साथ अपडेट रहें',
    'schemes.description': 'पीएम-किसान, मृदा स्वास्थ्य कार्ड योजना, प्रधानमंत्री फसल बीमा योजना और अन्य सरकारी पहलों के बारे में जानकारी जल्द ही यहां उपलब्ध होगी।',
    
    // Contact Section
    'contact.title': 'संपर्क में रहें',
    'contact.description': 'प्रश्न हैं या सहायता चाहिए? हम पूरे भारत में किसानों की मदद के लिए यहां हैं।',
    'contact.button': 'सहायता से संपर्क करें',
    
    // Footer
    'footer.collaboration': 'कृषि और किसान कल्याण मंत्रालय के सहयोग से (डेमो)',
    'footer.copyright': '© 2025 एग्रीविकास – भारत के किसानों को सशक्त बनाना',
    
    // Dashboard
    'dashboard.welcome': 'एग्रीविकास डैशबोर्ड में आपका स्वागत है',
    'dashboard.greeting': 'नमस्ते',
    'dashboard.message': 'आपका व्यक्तिगत फसल सलाह डैशबोर्ड जल्द ही आ रहा है।',
    
    // Auth Page
    'auth.getStarted': 'शुरू करें',
    'auth.enterEmail': 'लॉग इन या साइन अप करने के लिए अपना ईमेल दर्ज करें',
    'auth.emailPlaceholder': 'name@example.com',
    'auth.or': 'या',
    'auth.continueGuest': 'अतिथि के रूप में जारी रखें',
    'auth.checkEmail': 'अपना ईमेल जांचें',
    'auth.codeSent': 'हमने एक कोड भेजा है',
    'auth.didntReceive': 'कोड प्राप्त नहीं हुआ?',
    'auth.tryAgain': 'पुनः प्रयास करें',
    'auth.verifyCode': 'कोड सत्यापित करें',
    'auth.verifying': 'सत्यापित कर रहे हैं...',
    'auth.useDifferentEmail': 'अलग ईमेल का उपयोग करें',
    'auth.securedBy': 'द्वारा सुरक्षित',
    
    // Not Found
    'notFound.title': '404',
    'notFound.message': 'पृष्ठ नहीं मिला',
    
    // Chatbot
    'chatbot.title': 'एग्रीविकास स्मार्ट वॉयस असिस्टेंट',
    'chatbot.placeholder': 'मुझसे मौसम, सिंचाई या फसल सहायता के बारे में पूछें…',
    'chatbot.inputPlaceholder': 'अपना संदेश टाइप करें...',
    'chatbot.voiceInput': 'वॉयस इनपुट',
    'chatbot.recording': 'रिकॉर्डिंग...',
    'chatbot.error.microphone': 'माइक्रोफ़ोन एक्सेस अस्वीकृत या अनुपलब्ध',
    'chatbot.error.notSupported': 'इस ब्राउज़र में स्पीच रिकग्निशन समर्थित नहीं है',
    'chatbot.clearChat': 'चैट साफ़ करें',
    
    // Dashboard Navigation
    'dashboard.title': 'डैशबोर्ड',
    'dashboard.nav.home': 'डैशबोर्ड',
    'dashboard.nav.profile': 'My Profile',
    'dashboard.nav.advisory': 'स्मार्ट फसल सलाह',
    'dashboard.nav.irrigation': 'सिंचाई अलर्ट',
    'dashboard.nav.disease': 'रोग पहचान',
    'dashboard.nav.schemes': 'सरकारी योजनाएं और सब्सिडी',
    'dashboard.nav.mandi': 'मंडी भाव',
    'dashboard.nav.insights': 'खेत की जानकारी',
    'dashboard.nav.chat': 'चैट सहायक',
    'dashboard.nav.settings': 'सेटिंग्स',
    'dashboard.logout': 'लॉग आउट',
    
    // Dashboard Home
    'dashboard.home.welcome': 'स्वागत है',
    'dashboard.home.subtitle': 'आपकी व्यक्तिगत कृषि जानकारी',
    'dashboard.home.weather': 'मौसम अभी',
    'dashboard.home.irrigation': 'अगली सिंचाई',
    'dashboard.home.irrigationValue': '{days} दिनों में',
    'dashboard.home.cropHealth': 'फसल स्वास्थ्य स्थिति',
    'dashboard.home.cropHealthValue': 'अच्छा - कोई समस्या नहीं',
    'dashboard.home.schemes': 'नई योजनाएं उपलब्ध',
    'dashboard.home.schemesValue': '{count} योजनाएं',
    'dashboard.home.latestSchemes': 'नवीनतम सरकारी योजनाएं',
    'dashboard.home.knowMore': 'और जानें',
    
    // Dashboard Home - add these new keys after existing dashboard.home translations
    'dashboard.home.futureEnhancements': 'भविष्य के सुधार',
    'dashboard.home.yieldPrediction': 'AI उपज भविष्यवाणी',
    'dashboard.home.yieldPredictionDesc': 'बेहतर योजना के लिए AI और ऐतिहासिक डेटा का उपयोग करके फसल उपज की भविष्यवाणी करें',
    'dashboard.home.waterTracker': 'जल उपयोग ट्रैकर डैशबोर्ड',
    'dashboard.home.waterTrackerDesc': 'अपने खेत में पानी की खपत की निगरानी और अनुकूलन करें',
    'dashboard.home.smsAccess': 'ऑफलाइन SMS एक्सेस',
    'dashboard.home.smsAccessDesc': 'इंटरनेट के बिना फीचर-फोन किसानों के लिए SMS के माध्यम से सलाह प्राप्त करें',
    'dashboard.home.portalIntegration': 'एग्री पंजाब पोर्टल एकीकरण',
    'dashboard.home.portalIntegrationDesc': 'data.gov.in और पंजाब कृषि पोर्टल के साथ निर्बाध एकीकरण',
    'dashboard.home.comingSoon': 'जल्द आ रहा है',
    
    // Government Schemes
    'dashboard.schemes.pmkisan.title': 'पीएम-किसान योजना',
    'dashboard.schemes.pmkisan.description': 'छोटे और सीमांत किसानों को ₹6,000/वर्ष की प्रत्यक्ष आय सहायता',
    'dashboard.schemes.pmfby.title': 'पीएमएफबीवाई फसल बीमा',
    'dashboard.schemes.pmfby.description': 'प्राकृतिक आपदाओं के खिलाफ व्यापक फसल बीमा',
    'dashboard.schemes.pmfby.coverage': 'पूर्ण कवरेज',
    'dashboard.schemes.soilHealth.title': 'मृदा स्वास्थ्य कार्ड योजना',
    'dashboard.schemes.soilHealth.description': 'मुफ्त मिट्टी परीक्षण और पोषक तत्व प्रबंधन सलाह',
    'dashboard.schemes.soilHealth.free': 'मुफ्त सेवा',
    
    // Irrigation Alerts Section
    'irrigation.title': 'स्मार्ट सिंचाई अलर्ट',
    'irrigation.subtitle': 'पानी और ऊर्जा बचाने के लिए मौसम-आधारित सिंचाई सिफारिशें',
    'irrigation.selectLocation': 'स्थान चुनें',
    'irrigation.weather': 'मौसम',
    'irrigation.refresh': 'मौसम रिफ्रेश करें',
    'irrigation.temperature': 'तापमान',
    'irrigation.humidity': 'आर्द्रता',
    'irrigation.condition': 'स्थिति',
    'irrigation.adviceTitle': 'सिंचाई सलाह',
    'irrigation.clickRefresh': 'लाइव डेटा और सिंचाई सलाह प्राप्त करने के लिए "मौसम रिफ्रेश करें" पर क्लिक करें',
    'irrigation.weatherUpdated': 'मौसम डेटा सफलतापूर्वक अपडेट किया गया',
    'irrigation.usingSimulatedData': 'डेमो के लिए सिम्युलेटेड डेटा का उपयोग कर रहे हैं',
    'irrigation.tip': 'सुझाव',
    'irrigation.tipText': 'सर्वोत्तम परिणामों के लिए सुबह जल्दी या शाम को अपनी फसलों को पानी दें',
    'irrigation.bestPractices': 'सर्वोत्तम सिंचाई प्रथाएं',
    'irrigation.practice1': 'वाष्पीकरण कम करने के लिए सुबह जल्दी (5-7 बजे) या शाम (6-8 बजे) पानी दें',
    'irrigation.practice2': 'सिंचाई से पहले मिट्टी की नमी जांचें - अधिक पानी देने से बचें',
    'irrigation.practice3': '40% तक पानी बचाने के लिए ड्रिप सिंचाई प्रणाली का उपयोग करें',
    'irrigation.practice4': 'मौसम पूर्वानुमान की निगरानी करें और यदि बारिश की उम्मीद है तो सिंचाई छोड़ दें',
    'irrigation.advice.skipRain': '🌧️ आज बारिश की संभावना है — पानी और ऊर्जा बचाने के लिए सिंचाई छोड़ दें',
    'irrigation.advice.highTemp': '🌡️ उच्च तापमान और कम आर्द्रता — सर्वोत्तम परिणामों के लिए शाम को सिंचाई करें',
    'irrigation.advice.highHumidity': '💧 उच्च आर्द्रता का पता चला — फंगल वृद्धि को रोकने के लिए सिंचाई की आवृत्ति कम करें',
    'irrigation.advice.lowTemp': '❄️ ठंडा मौसम — वाष्पीकरण कम होने के कारण सिंचाई की आवृत्ति कम करें',
    'irrigation.advice.normal': '✅ मौसम की स्थिति सामान्य है — नियमित कार्यक्रम के अनुसार सिंचाई करें',
    
    // Smart Crop Advisory
    'advisory.title': 'स्मार्ट फसल सलाह',
    'advisory.subtitle': 'टिकाऊ खेती के लिए व्यक्तिगत फसल सिफारिशें प्राप्त करें',
    'advisory.getAdvisory': 'सलाह प्राप्त करें',
    'advisory.landArea': 'भूमि क्षेत्र (एकड़)',
    'advisory.soilType': 'मिट्टी का प्रकार',
    'advisory.currentCrop': 'वर्तमान फसल',
    'advisory.district': 'जिला',
    'advisory.waterAvailability': 'पानी की उपलब्धता',
    'advisory.recommendedCrops': 'अनुशंसित फसलें',
    'advisory.advice': 'खेती सलाह',
    'advisory.cropComparison': 'फसल तुलना',
    'advisory.waterUse': 'पानी का उपयोग',
    'advisory.profit': 'लाभ क्षमता',
    'advisory.soilImpact': 'मिट्टी प्रभाव',
    'advisory.speakAdvice': 'सलाह बोलें',
    'advisory.history': 'सलाह इतिहास',
    
    // Mandi Prices
    'mandi.title': 'लाइव मंडी भाव',
    'mandi.subtitle': 'भारत सरकार के AGMARKNET डेटा (data.gov.in) से फसलों के वास्तविक समय के थोक बाजार भाव',
    'mandi.live': 'लाइव',
    'mandi.offline': 'सेटअप आवश्यक',
    'mandi.chooseCrops': 'फसलें और जिला चुनें',
    'mandi.district': 'जिला',
    'mandi.getPrices': 'लाइव भाव प्राप्त करें',
    'mandi.market': 'मंडी',
    'mandi.variety': 'किस्म',
    'mandi.minPrice': 'न्यूनतम',
    'mandi.maxPrice': 'अधिकतम',
    'mandi.modalPrice': 'मुख्य भाव',
    'mandi.arrivalDate': 'आवक तिथि',
    'mandi.unit': 'इकाई',
    'mandi.updated': 'अपडेटेड',

    // Government Schemes
    'schemes.findSchemes': 'योजनाएं खोजें',
    'schemes.farmerCategory': 'किसान श्रेणी',
    'schemes.cropType': 'फसल का प्रकार',
    'schemes.district': 'जिला',
    'schemes.irrigationMethod': 'सिंचाई विधि',
    'schemes.recommendedSchemes': 'अनुशंसित योजनाएं',
    'schemes.history': 'खोज इतिहास',
    'schemes.selectCategory': 'श्रेणी चुनें',
    'schemes.selectCrop': 'फसल चुनें',
    'schemes.selectDistrict': 'जिला चुनें',
    'schemes.selectMethod': 'विधि चुनें',
    'schemes.optional': 'वैकल्पिक',
    'schemes.searching': 'खोज रहे हैं...',
    'schemes.eligibility': 'पात्रता',
    'schemes.whyScheme': 'यह योजना क्यों?',
    'schemes.applyNow': 'अभी आवेदन करें',
    'schemes.enterDetails': 'प्रासंगिक सरकारी योजनाएं खोजने के लिए अपना विवरण दर्ज करें',
    'schemes.clickToView': 'योजनाओं को फिर से देखने के लिए किसी भी खोज पर क्लिक करें',
    'schemes.schemesFound': 'योजनाएं मिलीं',
    'schemes.farmer': 'किसान',
    'schemes.viewing': '✓ देख रहे हैं',
    'schemes.fillRequired': 'कृपया आवश्यक फ़ील्ड भरें',
    'schemes.foundSuccess': 'योजनाएं मिलीं!',
    'schemes.findFailed': 'योजनाएं खोजने में विफल',
    'schemes.loadedHistory': 'इतिहास से योजनाएं लोड की गईं',
    
    // Farmer Profile
    'profile.title': 'किसान प्रोफ़ाइल',
    'profile.subtitle': 'व्यक्तिगत सिफारिशों के लिए अपनी प्रोफ़ाइल पूरी करें',
    'profile.fullName': 'पूरा नाम',
    'profile.district': 'जिला',
    'profile.landArea': 'भूमि क्षेत्र (एकड़)',
    'profile.soilType': 'मिट्टी का प्रकार',
    'profile.waterAvailability': 'पानी की उपलब्धता',
    'profile.crops': 'उगाई गई फसलें',
    'profile.language': 'पसंदीदा भाषा',
    'profile.saveProfile': 'प्रोफ़ाइल सहेजें',
    'profile.updateProfile': 'प्रोफ़ाइल अपडेट करें',
    'profile.profileSaved': '✅ किसान प्रोफ़ाइल सफलतापूर्वक सहेजी गई! व्यक्तिगत सलाह सक्रिय।',
    'profile.profileUpdated': '✅ प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!',
    'profile.fillAllFields': 'कृपया सभी आवश्यक फ़ील्ड भरें',
    'profile.selectDistrict': 'अपना जिला चुनें',
    'profile.selectSoilType': 'मिट्टी का प्रकार चुनें',
    'profile.selectWaterAvailability': 'पानी की उपलब्धता चुनें',
    'profile.selectCrops': 'अपनी फसलें चुनें',
    'profile.low': 'कम',
    'profile.medium': 'मध्यम',
    'profile.high': 'उच्च',
    'profile.loamy': 'दोमट',
    'profile.sandy': 'रेतीली',
    'profile.clay': 'चिकनी',
    'profile.alluvial': 'जलोढ़',
    'profile.wheat': 'गेहूं',
    'profile.rice': 'चावल/धान',
    'profile.maize': 'मक्का',
    'profile.cotton': 'कपास',
    'profile.sugarcane': 'गन्ना',
    'profile.pulses': 'दालें',
    'profile.vegetables': 'सब्जियां',
  },
  pa: {
    // Header
    'header.title': 'ਐਗਰੀਵਿਕਾਸ',
    'header.subtitle': 'ਛੋਟੇ ਅਤੇ ਸੀਮਾਂਤ ਕਿਸਾਨਾਂ ਲਈ ਸਮਾਰਟ ਫਸਲ ਸਲਾਹ',
    'header.home': 'ਹੋਮ',
    'header.about': 'ਸਾਡੇ ਬਾਰੇ',
    'header.features': 'ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ',
    'header.schemes': 'ਯੋਜਨਾਵਾਂ',
    'header.contact': 'ਸੰਪਰਕ',
    'header.signIn': 'ਸਾਈਨ ਇਨ',
    'header.guestLogin': 'ਮਹਿਮਾਨ ਲੌਗਇਨ',
    'header.menu': 'ਮੀਨੂ',
    
    // Language Selector
    'lang.english': 'English',
    'lang.hindi': 'हिंदी (Hindi)',
    'lang.punjabi': 'ਪੰਜਾਬੀ (Punjabi)',
    
    // Hero Section
    'hero.tagline': 'ਸਮਾਰਟ ਫਸਲ ਫੈਸਲੇ, ਪਾਣੀ ਦੀ ਬਚਤ ਅਤੇ ਸਮੇਂ ਸਿਰ ਚੇਤਾਵਨੀਆਂ ਨਾਲ ਕਿਸਾਨਾਂ ਨੂੰ ਸ਼ਕਤੀਕਰਨ',
    'hero.description': 'ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਵਿਅਕਤੀਗਤ ਫਸਲ ਸਲਾਹ, ਸਿੰਚਾई ਚੇਤਾਵਨੀਆਂ ਅਤੇ AI-ਸੰਚਾਲਿਤ ਸਿਹਤ ਪਛਾਣ ਪ੍ਰਾਪਤ ਕਰੋ',
    'hero.exploreGuest': 'ਮਹਿਮਾਨ ਵਜੋਂ ਦੇਖੋ',
    'hero.signInDashboard': 'ਆਪਣੇ ਡੈਸ਼ਬੋਰਡ ਵਿੱਚ ਸਾਈਨ ਇਨ ਕਰੋ',
    
    // Features Section
    'features.title': 'ਮੁੱਖ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ',
    'features.subtitle': 'ਭਾਰਤੀ ਕਿਸਾਨਾਂ ਲਈ ਖਾਸ ਤੌਰ ਤੇ ਤਿਆਰ ਕੀਤੀ ਆਧੁਨਿਕ ਤਕਨਾਲੋਜੀ',
    'features.scrollCue': 'ਐਗਰੀਵਿਕਾਸ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ ਦੇਖੋ',
    'features.irrigation.title': 'ਸਮਾਰਟ ਸਿੰਚਾई ਚੇਤਾਵਨੀਆਂ',
    'features.irrigation.description': 'ਪਾਣੀ ਅਤੇ ਊਰਜਾ ਬਚਾਉਣ ਲਈ ਮੌਸਮ-ਆਧਾਰਿਤ ਸਿੰਚਾई ਸਿਫਾਰਸ਼ਾਂ ਪ੍ਰਾਪਤ ਕਰੋ',
    'features.irrigation.badge': '40% ਪਾਣੀ ਬਚਾਓ',
    'features.health.title': 'AI ਫਸਲ ਬਿਮਾਰੀ ਪਛਾਣ',
    'features.health.description': 'ਪੱਤੇ ਦੀਆਂ ਤਸਵੀਰਾਂ ਅੱਪਲੋਡ ਕਰੋ ਅਤੇ ਮਸ਼ੀਨ ਲਰਨਿੰਗ ਦੀ ਵਰਤੋਂ ਕਰਕੇ ਬਿਮਾਰੀਆਂ ਦਾ ਜਲਦੀ ਪਤਾ ਲਗਾਓ',
    'features.health.badge': 'ਜਲਦੀ ਪਛਾਣ',
    'features.advisory.title': 'ਸਮਾਰਟ ਫਸਲ ਸਲਾਹ',
    'features.advisory.description': 'ਮਿੱਟੀ, ਮੌਸਮ ਅਤੇ ਮੌਸਮ ਦੇ ਆਧਾਰ ਤੇ ਵਿਅਕਤੀਗਤ ਫਸਲ ਸੁਝਾਅ',
    'features.advisory.badge': 'AI ਸੰਚਾਲਿਤ',
    'features.schemes.title': 'ਸਰਕਾਰੀ ਯੋਜਨਾ ਅਤੇ ਸਬਸਿਡੀ ਜਾਗਰੂਕਤਾ',
    'features.schemes.description': 'PM-KISAN, MSP, ਅਤੇ ਉਪਕਰਣ ਸਬਸਿਡੀਆਂ ਬਾਰੇ ਅੱਪਡੇਟ ਰਹੋ। ਛੋਟੇ ਅਤੇ ਸੀਮਾਂਤ ਕਿਸਾਨਾਂ ਲਈ ਜਾਣਕਾਰੀ ਦੇ ਪਾੜੇ ਨੂੰ ਪੂਰਾ ਕਰਦਾ ਹੈ',
    'features.schemes.badge': 'ਸੂਚਿਤ ਰਹੋ',
    'features.diversification.title': 'ਫਸਲ ਵਿਭਿੰਨਤਾ ਸਹਾਇਤਾ',
    'features.diversification.description': 'ਟਿਕਾਊ ਫਸਲਾਂ ਵੱਲ ਤਬਦੀਲ ਹੋ ਕੇ ਮਿੱਟੀ ਦੀ ਉਪਜਾਊ ਸ਼ਕਤੀ ਅਤੇ ਪਾਣੀ ਦੀ ਬਚਤ ਨੂੰ ਉਤਸ਼ਾਹਿਤ ਕਰੋ',
    'features.diversification.badge': 'ਟਿਕਾਊ',
    'features.multilingual.title': 'ਬਹੁ-ਭਾਸ਼ਾਈ ਸੰਚਾਰ',
    'features.multilingual.description': 'ਐਪ, SMS, ਅਤੇ ਵੌਇਸ ਰਾਹੀਂ ਪੰਜਾਬੀ, ਹਿੰਦੀ ਅਤੇ ਅੰਗਰੇਜ਼ੀ ਵਿੱਚ ਸਲਾਹ ਪ੍ਰਾਪਤ ਕਰੋ—ਫੀਚਰ ਫੋਨਾਂ ਤੇ ਵੀ',
    'features.multilingual.badge': '3 ਭਾਸ਼ਾਵਾਂ',
    
    // About Section
    'about.title': 'ਐਗਰੀਵਿਕਾਸ ਬਾਰੇ',
    'about.description1': 'ਐਗਰੀਵਿਕਾਸ ਇੱਕ ਡਿਜੀਟਲ ਪਲੇਟਫਾਰਮ ਹੈ ਜੋ ਪੂਰੇ ਭਾਰਤ ਵਿੱਚ ਛੋਟੇ ਅਤੇ ਸੀਮਾਂਤ ਕਿਸਾਨਾਂ ਨੂੰ ਡੇਟਾ-ਸੰਚਾਲਿਤ ਖੇਤੀਬਾੜੀ ਜਾਣਕਾਰੀ ਨਾਲ ਸ਼ਕਤੀਕਰਨ ਕਰਨ ਲਈ ਤਿਆਰ ਕੀਤਾ ਗਿਆ ਹੈ। ਸਾਡਾ ਮਿਸ਼ਨ ਪੇਂਡੂ ਖੇਤੀਬਾੜੀ ਭਾਈਚਾਰਿਆਂ ਵਿੱਚ ਤਕਨਾਲੋਜੀ ਦੇ ਪਾੜੇ ਨੂੰ ਪੂਰਾ ਕਰਨਾ ਅਤੇ ਕਿਸਾਨਾਂ ਨੂੰ ਫਸਲ ਪ੍ਰਬੰਧਨ, ਸਿੰਚਾਈ ਅਤੇ ਕੀੜੇ ਨਿਯੰਤਰਣ ਬਾਰੇ ਸੂਚਿਤ ਫੈਸਲੇ ਲੈਣ ਵਿੱਚ ਮਦਦ ਕਰਨਾ ਹੈ।',
    'about.description2': 'ਖੇਤੀਬਾੜੀ ਮਾਹਰਾਂ ਦੇ ਸਮਰਥਨ ਨਾਲ ਬਣਾਇਆ ਗਿਆ ਅਤੇ AI ਦੁਆਰਾ ਸੰਚਾਲਿਤ, ਅਸੀਂ ਕਈ ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ ਸਮੇਂ ਸਿਰ, ਸਹੀ ਅਤੇ ਕਾਰਵਾਈਯੋਗ ਸਲਾਹ ਪ੍ਰਦਾਨ ਕਰਦੇ ਹਾਂ, ਇਹ ਯਕੀਨੀ ਬਣਾਉਂਦੇ ਹੋਏ ਕਿ ਹਰ ਕਿਸਾਨ ਆਧੁਨਿਕ ਤਕਨਾਲੋਜੀ ਤੋਂ ਲਾਭ ਲੈ ਸਕੇ।',
    
    // Schemes Section
    'schemes.title': 'ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ',
    'schemes.subtitle': 'ਨਵੀਨਤਮ ਖੇਤੀਬਾੜੀ ਯੋਜਨਾਵਾਂ ਅਤੇ ਸਬਸਿਡੀਆਂ ਨਾਲ ਅੱਪਡੇਟ ਰਹੋ',
    'schemes.description': 'PM-KISAN, ਮਿੱਟੀ ਸਿਹਤ ਕਾਰਡ ਯੋਜਨਾ, ਪ੍ਰਧਾਨ ਮੰਤਰੀ ਫਸਲ ਬੀਮਾ ਯੋਜਨਾ ਅਤੇ ਹੋਰ ਸਰਕਾਰੀ ਪਹਿਲਕਦਮੀਆਂ ਬਾਰੇ ਜਾਣਕਾਰੀ ਜਲਦੀ ਹੀ ਇੱਥੇ ਉਪਲਬਧ ਹੋਵੇਗੀ।',
    
    // Contact Section
    'contact.title': 'ਸੰਪਰਕ ਵਿੱਚ ਰਹੋ',
    'contact.description': 'ਸਵਾਲ ਹਨ ਜਾਂ ਸਹਾਇਤਾ ਦੀ ਲੋੜ ਹੈ? ਅਸੀਂ ਪੂਰੇ ਭਾਰਤ ਵਿੱਚ ਕਿਸਾਨਾਂ ਦੀ ਮਦਦ ਕਰਨ ਲਈ ਇੱਥੇ ਹਾਂ।',
    'contact.button': 'ਸਹਾਇਤਾ ਨਾਲ ਸੰਪਰਕ ਕਰੋ',
    
    // Footer
    'footer.collaboration': 'ਖੇਤੀਬਾੜੀ ਅਤੇ ਕਿਸਾਨ ਭਲਾਈ ਮੰਤਰਾਲੇ ਦੇ ਸਹਿਯੋਗ ਨਾਲ (ਡੈਮੋ)',
    'footer.copyright': '© 2025 ਐਗਰੀਵਿਕਾਸ – ਭਾਰਤ ਦੇ ਕਿਸਾਨਾਂ ਨੂੰ ਸ਼ਕਤੀਕਰਨ',
    
    // Dashboard
    'dashboard.welcome': 'ਐਗਰੀਵਿਕਾਸ ਡੈਸ਼ਬੋਰਡ ਵਿੱਚ ਤੁਹਾਡਾ ਸਵਾਗਤ ਹੈ',
    'dashboard.greeting': 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ',
    'dashboard.message': 'ਤੁਹਾਡਾ ਵਿਅਕਤੀਗਤ ਫਸਲ ਸਲਾਹ ਡੈਸ਼ਬੋਰਡ ਜਲਦੀ ਆ ਰਿਹਾ ਹੈ।',
    
    // Auth Page
    'auth.getStarted': 'ਸ਼ੁਰੂ ਕਰੋ',
    'auth.enterEmail': 'ਲੌਗ ਇਨ ਜਾਂ ਸਾਈਨ ਅੱਪ ਕਰਨ ਲਈ ਆਪਣਾ ਈਮੇਲ ਦਰਜ ਕਰੋ',
    'auth.emailPlaceholder': 'name@example.com',
    'auth.or': 'ਜਾਂ',
    'auth.continueGuest': 'ਮਹਿਮਾਨ ਵਜੋਂ ਜਾਰੀ ਰੱਖੋ',
    'auth.checkEmail': 'ਆਪਣਾ ਈਮੇਲ ਚੈੱਕ ਕਰੋ',
    'auth.codeSent': 'ਅਸੀਂ ਇੱਕ ਕੋਡ ਭੇਜਿਆ ਹੈ',
    'auth.didntReceive': 'ਕੋਡ ਪ੍ਰਾਪਤ ਨਹੀਂ ਹੋਇਆ?',
    'auth.tryAgain': 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
    'auth.verifyCode': 'ਕੋਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
    'auth.verifying': 'ਪੁਸ਼ਟੀ ਕਰ ਰਹੇ ਹਾਂ...',
    'auth.useDifferentEmail': 'ਵੱਖਰਾ ਈਮੇਲ ਵਰਤੋ',
    'auth.securedBy': 'ਦੁਆਰਾ ਸੁਰੱਖਿਅਤ',
    
    // Not Found
    'notFound.title': '404',
    'notFound.message': 'ਪੰਨਾ ਨਹੀਂ ਮਿਲਿਆ',
    
    // Chatbot
    'chatbot.title': 'ਐਗਰੀਵਿਕਾਸ ਸਮਾਰਟ ਵੌਇਸ ਅਸਿਸਟੈਂਟ',
    'chatbot.placeholder': 'ਮੈਨੂੰ ਮੌਸਮ, ਸਿੰਚਾई, ਜਾਂ ਫਸਲ ਸਹਾਇਤਾ ਬਾਰੇ ਪੁੱछੋ…',
    'chatbot.inputPlaceholder': 'ਆਪਣਾ ਸੁਨੇਹਾ ਟਾਈਪ ਕਰੋ...',
    'chatbot.voiceInput': 'ਵੌਇਸ ਇਨਪੁੱਟ',
    'chatbot.recording': 'ਰਿਕਾਰਡਿੰਗ...',
    'chatbot.error.microphone': 'ਮਾਈਕ੍ਰੋਫੋਨ ਪਹੁੰਚ ਅਸਵੀਕਾਰ ਜਾਂ ਉਪਲਬਧ ਨਹੀਂ',
    'chatbot.error.notSupported': 'ਇਸ ਬ੍ਰਾਊਜ਼ਰ ਵਿੱਚ ਸਪੀਚ ਰਿਕਗਨੀਸ਼ਨ ਸਮਰਥਿਤ ਨਹੀਂ ਹੈ',
    'chatbot.clearChat': 'ਚੈਟ ਸਾਫ਼ ਕਰੋ',
    
    // Dashboard Navigation
    'dashboard.title': 'ਡੈਸ਼ਬੋਰਡ',
    'dashboard.nav.home': 'ਡੈਸ਼ਬੋਰਡ',
    'dashboard.nav.profile': 'My Profile',
    'dashboard.nav.advisory': 'ਸਮਾਰਟ ਫਸਲ ਸਲਾਹ',
    'dashboard.nav.irrigation': 'ਸਿੰਚਾਈ ਚੇਤਾਵਨੀਆਂ',
    'dashboard.nav.disease': 'ਬਿਮਾਰੀ ਪਛਾਣ',
    'dashboard.nav.schemes': 'ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ ਅਤੇ ਸਬਸਿਡੀਆਂ',
    'dashboard.nav.mandi': 'ਮੰਡੀ ਭਾਅ',
    'dashboard.nav.insights': 'ਖੇਤ ਦੀ ਜਾਣਕਾਰੀ',
    'mandi.title': 'ਲਾਈਵ ਮੰਡੀ ਭਾਅ',
    'mandi.subtitle': 'ਭਾਰਤ ਸਰਕਾਰ ਦੇ AGMARKNET ਡੇਟਾ (data.gov.in) ਤੋਂ ਫਸਲਾਂ ਦੇ ਰੀਅਲ-ਟਾਈਮ ਥੋਕ ਮਾਰਕੀਟ ਭਾਅ',
    'mandi.live': 'ਲਾਈਵ',
    'mandi.offline': 'ਸੈੱਟਅੱਪ ਲੋੜੀਂਦਾ',
    'mandi.chooseCrops': 'ਫਸਲਾਂ ਅਤੇ ਜ਼ਿਲ੍ਹਾ ਚੁਣੋ',
    'mandi.district': 'ਜ਼ਿਲ੍ਹਾ',
    'mandi.getPrices': 'ਲਾਈਵ ਭਾਅ ਪ੍ਰਾਪਤ ਕਰੋ',
    'mandi.market': 'ਮੰਡੀ',
    'mandi.variety': 'ਕਿਸਮ',
    'mandi.minPrice': 'ਘੱਟੋ-ਘੱਟ',
    'mandi.maxPrice': 'ਵੱਧ ਤੋਂ ਵੱਧ',
    'mandi.modalPrice': 'ਮੁੱਖ ਭਾਅ',
    'mandi.arrivalDate': 'ਆਵਕ ਤਾਰੀਖ',
    'mandi.unit': 'ਇਕਾਈ',
    'mandi.updated': 'ਅੱਪਡੇਟ ਕੀਤਾ',
    'dashboard.nav.chat': 'ਚੈਟ ਸਹਾਇਕ',
    'dashboard.nav.settings': 'ਸੈਟਿੰਗਾਂ',
    'dashboard.logout': 'ਲੌਗ ਆਉਟ',
    
    // Dashboard Home
    'dashboard.home.welcome': 'ਸਵਾਗਤ ਹੈ',
    'dashboard.home.subtitle': 'ਤੁਹਾਡੀ ਵਿਅਕਤੀਗਤ ਖੇਤੀਬਾੜੀ ਜਾਣਕਾਰੀ',
    'dashboard.home.weather': 'ਮੌਸਮ ਹੁਣ',
    'dashboard.home.irrigation': 'ਅਗਲੀ ਸਿੰਚਾई',
    'dashboard.home.irrigationValue': '{days} ਦਿਨਾਂ ਵਿੱਚ',
    'dashboard.home.cropHealth': 'ਫਸਲ ਸਿਹਤ ਸਥਿਤੀ',
    'dashboard.home.cropHealthValue': 'ਚੰਗੀ - ਕੋਈ ਸਮੱਸਿਆ ਨਹੀਂ',
    'dashboard.home.schemes': 'ਨਵੀਆਂ ਯੋਜਨਾਵਾਂ ਉਪਲਬਧ',
    'dashboard.home.schemesValue': '{count} ਯੋਜਨਾਵਾਂ',
    'dashboard.home.latestSchemes': 'ਨਵੀਨਤਮ ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ',
    'dashboard.home.knowMore': 'ਹੋਰ ਜਾਣੋ',
    
    // Dashboard Home - add these new keys after existing dashboard.home translations
    'dashboard.home.futureEnhancements': 'ਭਵਿੱਖ ਦੇ ਸੁਧਾਰ',
    'dashboard.home.yieldPrediction': 'AI ਉਪਜ ਭਵਿੱਖਬਾਣੀ',
    'dashboard.home.yieldPredictionDesc': 'ਬਿਹਤਰ ਯੋਜਨਾ ਲਈ AI ਅਤੇ ਇਤਿਹਾਸਕ ਡੇਟਾ ਦੀ ਵਰਤੋਂ ਕਰਕੇ ਫਸਲ ਉਪਜ ਦੀ ਭਵਿੱਖਬਾਣੀ ਕਰੋ',
    'dashboard.home.waterTracker': 'ਪਾਣੀ ਵਰਤੋਂ ਟ੍ਰੈਕਰ ਡੈਸ਼ਬੋਰਡ',
    'dashboard.home.waterTrackerDesc': 'ਆਪਣੇ ਖੇਤ ਵਿੱਚ ਪਾਣੀ ਦੀ ਖਪਤ ਦੀ ਨਿਗਰਾਨੀ ਅਤੇ ਅਨੁਕੂਲਨ ਕਰੋ',
    'dashboard.home.smsAccess': 'ਆਫਲਾਈਨ SMS ਪਹੁੰਚ',
    'dashboard.home.smsAccessDesc': 'ਇੰਟਰਨੈੱਟ ਤੋਂ ਬਿਨਾਂ ਫੀਚਰ-ਫੋਨ ਕਿਸਾਨਾਂ ਲਈ SMS ਰਾਹੀਂ ਸਲਾਹ ਪ੍ਰਾਪਤ ਕਰੋ',
    'dashboard.home.portalIntegration': 'ਐਗਰੀ ਪੰਜਾਬ ਪੋਰਟਲ ਏਕੀਕਰਣ',
    'dashboard.home.portalIntegrationDesc': 'data.gov.in ਅਤੇ ਪੰਜਾਬ ਖੇਤੀਬਾੜੀ ਪੋਰਟਲ ਨਾਲ ਸਹਿਜ ਏਕੀਕਰਣ',
    'dashboard.home.comingSoon': 'ਜਲਦੀ ਆ ਰਿਹਾ ਹੈ',
    
    // Government Schemes
    'dashboard.schemes.pmkisan.title': 'ਪੀਐਮ-ਕਿਸਾਨ ਯੋਜਨਾ',
    'dashboard.schemes.pmkisan.description': 'ਛੋਟੇ ਅਤੇ ਸੀਮਾਂਤ ਕਿਸਾਨਾਂ ਨੂੰ ₹6,000/ਸਾਲ ਦੀ ਸਿੱਧੀ ਆਮਦਨ ਸਹਾਇਤਾ',
    'dashboard.schemes.pmfby.title': 'ਪੀਐਮਐਫਬੀਵਾਈ ਫਸਲ ਬੀਮਾ',
    'dashboard.schemes.pmfby.description': 'ਕੁਦਰਤੀ ਆਫ਼ਤਾਂ ਦੇ ਵਿਰੁੱਧ ਵਿਆਪਕ ਫਸਲ ਬੀਮਾ',
    'dashboard.schemes.pmfby.coverage': 'ਪੂਰੀ ਕਵਰੇਜ',
    'dashboard.schemes.soilHealth.title': 'ਮਿੱਟੀ ਸਿਹਤ ਕਾਰਡ ਯੋਜਨਾ',
    'dashboard.schemes.soilHealth.description': 'ਮੁਫ਼ਤ ਮਿੱਟੀ ਜਾਂਚ ਅਤੇ ਪੋਸ਼ਕ ਤੱਤ ਪ੍ਰਬੰਧਨ ਸਲਾਹ',
    'dashboard.schemes.soilHealth.free': 'ਮੁਫ਼ਤ ਸੇਵਾ',
    
    // Irrigation Alerts Section
    'irrigation.title': 'ਸਮਾਰਟ ਸਿੰਚਾई ਚੇਤਾਵਨੀਆਂ',
    'irrigation.subtitle': 'ਪਾਣੀ ਅਤੇ ਊਰਜਾ ਬਚਾਉਣ ਲਈ ਮੌਸਮ-ਆਧਾਰਿਤ ਸਿੰਚਾई ਸਿਫਾਰਸ਼ਾਂ',
    'irrigation.selectLocation': 'ਸਥਾਨ ਚੁਣੋ',
    'irrigation.weather': 'ਮੌਸਮ',
    'irrigation.refresh': 'ਮੌਸਮ ਰਿਫ੍ਰੈਸ਼ ਕਰੋ',
    'irrigation.temperature': 'ਤਾਪਮਾਨ',
    'irrigation.humidity': 'ਨਮੀ',
    'irrigation.condition': 'ਸਥਿਤੀ',
    'irrigation.adviceTitle': 'ਸਿੰਚਾਈ ਸਲਾਹ',
    'irrigation.clickRefresh': 'ਲਾਈਵ ਡੇਟਾ ਅਤੇ ਸਿੰਚਾई ਸਲਾਹ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ "ਮੌਸਮ ਰਿਫ੍ਰੈਸ਼ ਕਰੋ" ਤੇ ਕਲਿੱਕ ਕਰੋ',
    'irrigation.weatherUpdated': 'ਮੌਸਮ ਡੇਟਾ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਕੀਤਾ ਗਿਆ',
    'irrigation.usingSimulatedData': 'ਡੈਮੋ ਲਈ ਸਿਮੂਲੇਟਿਡ ਡੇਟਾ ਦੀ ਵਰਤੋਂ ਕਰ ਰਹੇ ਹਾਂ',
    'irrigation.tip': 'ਸੁਝਾਅ',
    'irrigation.tipText': 'ਸਰਵੋਤਮ ਨਤੀਜਿਆਂ ਲਈ ਸਵੇਰੇ ਜਲਦੀ ਜਾਂ ਸ਼ਾਮ ਨੂੰ ਆਪਣੀਆਂ ਫਸਲਾਂ ਨੂੰ ਪਾਣੀ ਦਿਓ',
    'irrigation.bestPractices': 'ਸਰਵੋਤਮ ਸਿੰਚਾई ਅਭਿਆਸ',
    'irrigation.practice1': 'ਵਾਸ਼ਪੀਕਰਨ ਘਟਾਉਣ ਲਈ ਸਵੇਰੇ ਜਲਦੀ (5-7 ਵਜੇ) ਜਾਂ ਸ਼ਾਮ (6-8 ਵਜੇ) ਪਾਣੀ ਦਿਓ',
    'irrigation.practice2': 'ਸਿੰਚਾई ਤੋਂ ਪਹਿਲਾਂ ਮਿੱਟੀ ਦੀ ਨਮੀ ਦੀ ਜਾਂਚ ਕਰੋ - ਜ਼ਿਆਦਾ ਪਾਣੀ ਦੇਣ ਤੋਂ ਬਚੋ',
    'irrigation.practice3': '40% ਤੱਕ ਪਾਣੀ ਬਚਾਉਣ ਲਈ ਡ੍ਰਿਪ ਸਿੰਚਾई ਪ੍ਰਣਾਲੀਆਂ ਦੀ ਵਰਤੋਂ ਕਰੋ',
    'irrigation.practice4': 'ਮੌਸਮ ਦੀ ਭਵਿੱਖਬਾਣੀ ਦੀ ਨਿਗਰਾਨੀ ਕਰੋ ਅਤੇ ਜੇ ਬਾਰਿਸ਼ ਦੀ ਉਮੀਦ ਹੈ ਤਾਂ ਸਿੰਚਾई ਛੱਡ ਦਿਓ',
    'irrigation.advice.skipRain': '🌧️ ਅੱਜ ਬਾਰਿਸ਼ ਦੀ ਸੰਭਾਵਨਾ ਹੈ — ਪਾਣੀ ਅਤੇ ਊਰਜਾ ਬਚਾਉਣ ਲਈ ਸਿੰਚਾई ਛੱਡ ਦਿਓ',
    'irrigation.advice.highTemp': '🌡️ ਉੱਚ ਤਾਪਮਾਨ ਅਤੇ ਘੱਟ ਨਮੀ — ਸਰਵੋਤਮ ਨਤੀਜਿਆਂ ਲਈ ਸ਼ਾਮ ਨੂੰ ਸਿੰਚਾई ਕਰੋ',
    'irrigation.advice.highHumidity': '💧 ਉੱਚ ਨਮੀ ਦਾ ਪਤਾ ਲੱਗਾ — ਫੰਗਲ ਵਾਧੇ ਨੂੰ ਰੋਕਣ ਲਈ ਸਿੰਚਾई ਦੀ ਬਾਰੰਬਾਰਤਾ ਘਟਾਓ',
    'irrigation.advice.lowTemp': '❄️ ਠੰਡਾ ਮੌਸਮ — ਵਾਸ਼ਪੀਕਰਨ ਘੱਟ ਹੋਣ ਕਾਰਨ ਸਿੰਚਾई ਦੀ ਬਾਰੰਬਾਰਤਾ ਘਟਾਓ',
    'irrigation.advice.normal': '✅ ਮੌਸਮ ਦੀਆਂ ਸਥਿਤੀਆਂ ਆਮ ਹਨ — ਨਿਯਮਤ ਸਮਾਂ-ਸਾਰਣੀ ਅਨੁਸਾਰ ਸਿੰਚਾई ਕਰੋ',
    
    // Smart Crop Advisory
    'advisory.title': 'ਸਮਾਰਟ ਫਸਲ ਸਲਾਹ',
    'advisory.subtitle': 'ਟਿਕਾਊ ਖੇਤੀ ਲਈ ਵਿਅਕਤੀਗਤ ਫਸਲ ਸਿਫਾਰਸ਼ਾਂ ਪ੍ਰਾਪਤ ਕਰੋ',
    'advisory.getAdvisory': 'ਸਲਾਹ ਪ੍ਰਾਪਤ ਕਰੋ',
    'advisory.landArea': 'ਜ਼ਮੀਨ ਖੇਤਰ (ਏਕੜ)',
    'advisory.soilType': 'ਮਿੱਟੀ ਦੀ ਕਿਸਮ',
    'advisory.currentCrop': 'ਮੌਜੂਦਾ ਫਸਲ',
    'advisory.district': 'ਜ਼ਿਲ੍ਹਾ',
    'advisory.waterAvailability': 'ਪਾਣੀ ਦੀ ਉਪਲਬਧਤਾ',
    'advisory.recommendedCrops': 'ਸਿਫਾਰਸ਼ ਕੀਤੀਆਂ ਫਸਲਾਂ',
    'advisory.advice': 'ਖੇਤੀ ਸਲਾਹ',
    'advisory.cropComparison': 'ਫਸਲ ਤੁਲਨਾ',
    'advisory.waterUse': 'ਪਾਣੀ ਦੀ ਵਰਤੋਂ',
    'advisory.profit': 'ਲਾਭ ਸੰਭਾਵਨਾ',
    'advisory.soilImpact': 'ਮਿੱਟੀ ਪ੍ਰਭਾਵ',
    'advisory.speakAdvice': 'ਸਲਾਹ ਬੋਲੋ',
    'advisory.history': 'ਸਲਾਹ ਇਤਿਹਾਸ',
    
    // Government Schemes
    'schemes.findSchemes': 'ਯੋਜਨਾਵਾਂ ਲੱਭੋ',
    'schemes.farmerCategory': 'ਕਿਸਾਨ ਸ਼੍ਰੇਣੀ',
    'schemes.cropType': 'ਫਸਲ ਦੀ ਕਿਸਮ',
    'schemes.district': 'ਜ਼ਿਲ੍ਹਾ',
    'schemes.irrigationMethod': 'ਸਿੰਚਾਈ ਵਿਧੀ',
    'schemes.recommendedSchemes': 'ਸਿਫਾਰਸ਼ ਕੀਤੀਆਂ ਯੋਜਨਾਵਾਂ',
    'schemes.history': 'ਖੋਜ ਇਤਿਹਾਸ',
    'schemes.selectCategory': 'ਸ਼੍ਰੇਣੀ ਚੁਣੋ',
    'schemes.selectCrop': 'ਫਸਲ ਚੁਣੋ',
    'schemes.selectDistrict': 'ਜ਼ਿਲ੍ਹਾ ਚੁਣੋ',
    'schemes.selectMethod': 'ਵਿਧੀ ਚੁਣੋ',
    'schemes.optional': 'ਵਿਕਲਪਿਕ',
    'schemes.searching': 'ਖੋਜ ਰਹੇ ਹਾਂ...',
    'schemes.eligibility': 'ਯੋਗਤਾ',
    'schemes.whyScheme': 'ਇਹ ਯੋਜਨਾ ਕਿਉਂ?',
    'schemes.applyNow': 'ਹੁਣੇ ਅਰਜ਼ੀ ਦਿਓ',
    'schemes.enterDetails': 'ਸੰਬੰਧਿਤ ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ ਲੱਭਣ ਲਈ ਆਪਣਾ ਵੇਰਵਾ ਦਰਜ ਕਰੋ',
    'schemes.clickToView': 'ਯੋਜਨਾਵਾਂ ਦੁਬਾਰਾ ਦੇਖਣ ਲਈ ਕਿਸੇ ਵੀ ਖੋਜ \'ਤੇ ਕਲਿੱਕ ਕਰੋ',
    'schemes.schemesFound': 'ਯੋਜਨਾਵਾਂ ਮਿਲੀਆਂ',
    'schemes.farmer': 'ਕਿਸਾਨ',
    'schemes.viewing': '✓ ਦੇਖ ਰਹੇ ਹੋ',
    'schemes.fillRequired': 'ਕਿਰਪਾ ਕਰਕੇ ਲੋੜੀਂਦੇ ਖੇਤਰ ਭਰੋ',
    'schemes.foundSuccess': 'ਯੋਜਨਾਵਾਂ ਮਿਲੀਆਂ!',
    'schemes.findFailed': 'ਯੋਜਨਾਵਾਂ ਲੱਭਣ ਵਿੱਚ ਅਸਫਲ',
    'schemes.loadedHistory': 'ਇਤਿਹਾਸ ਤੋਂ ਯੋਜਨਾਵਾਂ ਲੋਡ ਕੀਤੀਆਂ ਗਈਆਂ',
    
    // Farmer Profile
    'profile.title': 'ਕਿਸਾਨ ਪ੍ਰੋਫਾਈਲ',
    'profile.subtitle': 'ਵਿਅਕਤੀਗਤ ਸਿਫਾਰਸ਼ਾਂ ਲਈ ਆਪਣੀ ਪ੍ਰੋਫਾਈਲ ਪੂਰੀ ਕਰੋ',
    'profile.fullName': 'ਪੂਰਾ ਨਾਮ',
    'profile.district': 'ਜ਼ਿਲ੍ਹਾ',
    'profile.landArea': 'ਜ਼ਮੀਨ ਖੇਤਰ (ਏਕੜ)',
    'profile.soilType': 'ਮਿੱਟੀ ਦੀ ਕਿਸਮ',
    'profile.waterAvailability': 'ਪਾਣੀ ਦੀ ਉਪਲਬਧਤਾ',
    'profile.crops': 'ਉਗਾਈਆਂ ਫਸਲਾਂ',
    'profile.language': 'ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ',
    'profile.saveProfile': 'ਪ੍ਰੋਫਾਈਲ ਸੁਰੱਖਿਅਤ ਕਰੋ',
    'profile.updateProfile': 'ਪ੍ਰੋਫਾਈਲ ਅੱਪਡੇਟ ਕਰੋ',
    'profile.profileSaved': '✅ ਕਿਸਾਨ ਪ੍ਰੋਫਾਈਲ ਸਫਲਤਾਪੂਰਵਕ ਸੁਰੱਖਿਅਤ ਕੀਤੀ ਗਈ! ਵਿਅਕਤੀਗਤ ਸਲਾਹ ਸਰਗਰਮ।',
    'profile.profileUpdated': '✅ ਪ੍ਰੋਫਾਈਲ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਕੀਤੀ ਗਈ!',
    'profile.fillAllFields': 'ਕਿਰਪਾ ਕਰਕੇ ਸਾਰੇ ਲੋੜੀਂਦੇ ਖੇਤਰ ਭਰੋ',
    'profile.selectDistrict': 'ਆਪਣਾ ਜ਼ਿਲ੍ਹਾ ਚੁਣੋ',
    'profile.selectSoilType': 'ਮਿੱਟੀ ਦੀ ਕਿਸਮ ਚੁਣੋ',
    'profile.selectWaterAvailability': 'ਪਾਣੀ ਦੀ ਉਪਲਬਧਤਾ ਚੁਣੋ',
    'profile.selectCrops': 'ਆਪਣੀਆਂ ਫਸਲਾਂ ਚੁਣੋ',
    'profile.low': 'ਘੱਟ',
    'profile.medium': 'ਮੱਧਮ',
    'profile.high': 'ਉੱਚ',
    'profile.loamy': 'ਦੋਮਟ',
    'profile.sandy': 'ਰੇਤਲੀ',
    'profile.clay': 'ਚਿਕਨੀ',
    'profile.alluvial': 'ਜਲੋਢ',
    'profile.wheat': 'ਕਣਕ',
    'profile.rice': 'ਚਾਵਲ/ਝੋਨਾ',
    'profile.maize': 'ਮੱਕੀ',
    'profile.cotton': 'ਕਪਾਹ',
    'profile.sugarcane': 'ਗੰਨਾ',
    'profile.pulses': 'ਦਾਲਾਂ',
    'profile.vegetables': 'ਸਬਜ਼ੀਆਂ',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('agrivikas-language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('agrivikas-language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const languageTranslations = translations[language];
    return (languageTranslations as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}